---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        app: hellosvc
      name: hellosvc
    spec:
      ports:
        - name: 9090-8080
          port: 9090
          protocol: TCP
          targetPort: 8080
      selector:
        app: hellosvc
      type: NodePort
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        app: hellosvc
      name: hellosvc
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: hellosvc
      strategy: { }
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: hellosvc
        spec:
          containers:
            - image: rbuhrmann/hellosvc
              name: hellosvc
              resources: { }
              imagePullPolicy: Always
    status: { }
