---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        app: hello-svc
      name: hello-svc
    spec:
      ports:
        - name: 9090-8080
          port: 9090
          protocol: TCP
          targetPort: 8080
      selector:
        app: hello-svc
      type: NodePort
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        app: hello-svc
      name: hello-svc
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: hello-svc
      strategy: { }
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: hello-svc
        spec:
          containers:
            - image: rbuhrmann/hello-svc:7f86e8464249a057484a60d8270bf9d11a71805f
              name: hello-svc
              resources: { }
    status: { }
