---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        app: hello-svc
      name: hello-svc
    spec:
      ports:
        - name: 9090-8080
          port: 9090
          protocol: TCP
          targetPort: 8080
      selector:
        app: hello-svc
      type: NodePort
    status:
      loadBalancer: {}